services:
  linux:
    image: mcr.microsoft.com/devcontainers/ruby:3.3-bookworm
    working_dir: /source
    volumes:
      - ../:/source
    environment:
      BUNDLE_GEMFILE: .devcontainer/Gemfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
